"""initial schema

Revision ID: b2105aadb1f5
Revises: 
Create Date: 2026-09-05 21:48:03.420368

"""
from alembic import op
import sqlalchemy as sa


revision = 'b2105aadb1f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EXPERT', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archive_ref', sa.String(), nullable=True),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('date_text', sa.String(), nullable=True),
    sa.Column('century', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('metadata_extra', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siyakat_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('cropped_image_path', sa.String(), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('read_value', sa.String(), nullable=True),
    sa.Column('variant_type', sa.String(), nullable=True),
    sa.Column('expert_note', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('grid_features', sa.JSON(), nullable=True),
    sa.Column('ductus_annotation', sa.JSON(), nullable=True),
    sa.Column('formal_features', sa.JSON(), nullable=True),
    sa.Column('philological_note', sa.Text(), nullable=True),
    sa.Column('alternative_interpretations', sa.JSON(), nullable=True),
    sa.Column('ai_prediction', sa.String(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_alternatives', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('field_changed', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['siyakat_samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_history')
    op.drop_table('siyakat_samples')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
